# Generated by Django 6.0.6 on 2026-06-04 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('warna_class', models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('teal', 'Teal'), ('red', 'Red')], default='pink', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengumuman', models.TextField(blank=True, help_text='Teks pengumuman yang muncul di sidebar halaman utama')),
            ],
            options={
                'verbose_name': 'Pengaturan Situs',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='anime/thumbnails/')),
                ('emoji', models.CharField(default='🎬', help_text='Emoji pengganti thumbnail', max_length=5)),
                ('warna_bg', models.CharField(default='linear-gradient(135deg,#1a0a2e,#4a1570)', help_text='CSS gradient untuk background card', max_length=100)),
                ('tipe', models.CharField(choices=[('sub', 'Subtitle'), ('dub', 'Dubbing'), ('baru', 'Baru')], default='sub', max_length=5)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Selesai'), ('upcoming', 'Akan Datang')], default='ongoing', max_length=10)),
                ('total_episode', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_populer', models.BooleanField(default=False)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharotta.genre')),
            ],
            options={
                'ordering': ['-dibuat'],
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.PositiveIntegerField(default=1)),
                ('isi', models.TextField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='sharotta.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat'],
            },
        ),
    ]
